### ISSUE TITLE
Add proxy environment and settings to playbook for proxy

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/de-ansible#11]
This is currently patched in roles/docker/tasks/main.yml

``` yml



- name: install/update docker-compose
  sudo: yes
  environment:
    https_proxy: {{ proxy_env.https_proxy }}
  get_url: url=https://github.com/docker/compose/releases/download/1.2.0/docker-compose-Linux-x86_64 dest=/usr/bin/docker-compose mode=0755 owner=docker group=docker validate_certs=no
  tags:
      - install_docker-compose



```

In group vars we added this setting

``` yml

proxy_env:
  http_proxy: http://proxy.bos.example.com:8080
  https_proxy: http://proxy.bos.example.com:8080



```

Change this to be global in relevant playbooks with a 'where' when proxies are needed
